### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hkalexling**
Great work but the readme file was unclear and had some obvious grammar mistakes

What did I do:
- use pure Markdown syntax
- make it more reader friendly
- fix some grammar mistakes

### CODE REVIEW

**Comment by aahung** [comment]
I cannot believe you made a contribution to my 2 year-old project. Thank you very much. Are you interested in it?

**Comment by hkalexling** [comment]
Yeah I think it's a helpful project and I can contribute more to it when I have time.

btw, I just found that the generated QR code gave me your email address and nothing more @@
Is this the way it was designed to be or did I do something wrong? (I am too lazy to open an issue so I just say it here XD)

**Comment by aahung** [comment]
Did you see this? After clicking "Get it"
screenshot from 2015-11-30 22-54-42

**Comment by hkalexling** [comment]
Oops it was my fault. I didn't click the "Get it" button.

Another problem: It works fine if you use phone to scan the QR code, but my browsers (both Safari and Chrome) can't find the server when I tried to download the schedule to my Mac.

screen shot 2015-11-30 at 11 18 00 pm

screen shot 2015-11-30 at 11 13 33 pm

**Comment by aahung** [comment]
Oh, that is my old website ideati.me, which I abandoned months ago. This is really an old project which I thought nobody would care. You made me want to rewrite it.

**Comment by hkalexling** [comment]
I think the idea is great, and the only problem is not many students know about this project. 

Anyway, good luck rewriting it :D

**Pull request merged**
